### ISSUE TITLE
[Discussion] neovim arduino-language-server

### ISSUE THREAD

**Issue by HannHank** [ac1dbyte/dots#1]
Hey,
I saw your [post](https://forum.arduino.cc/t/solved-errors-with-clangd-startup-for-arduino-language-server-in-nvim/1019977) on the Arduino platform, but unfortunately there is no way to leave a commend there. 

I am running into the same issue and even upgrading or downgrading the arduino-cli will not fix it. My setup is nearly the same as yours, apart from the fact that I use lsp-zero. 

The arduino-language-server is primarily focused on supporting the new Arduino IDE and perhaps things have changed that are now causing the issue again. 

Can you confirm that your setup with neovim and your lsp config is still working with the current version?

**Comment by amw1lson** [comment]
I haven't been on arduino in a while, but you're right, having just updated everything again i'm getting something like this: 
`[ERROR][2023-02-25 16:48:29] .../vim/lsp/rpc.lua:733	"rpc"	"arduino-language-server"	"stderr"	"16:48:29.531604 IN Elapsed: 7.548795ms\n16:48:29.531654 \27[92mIDE --> LS NOTIF initialized\27[0m\n16:48:29.531663 \27[92m                 initialized: Notification is not propagated to clangd\27[0m\n16:48:29.531952 IN Elapsed: 283.346µs\n16:48:29.531967 \27[92mIDE --> LS NOTIF textDocument/didOpen\27[0m\n"
[ERROR][2023-02-25 16:48:29] .../vim/lsp/rpc.lua:733	"rpc"	"arduino-language-server"	"stderr"	"16:48:29.532003 \27[92m                 textDocument/didOpen: \27[93mwrite-locked\27[0m\27[0m\n16:48:29.532008 \27[92m                 textDocument/didOpen: (throttled: waiting for clangd)\27[0m\n16:48:29.532012 \27[92m                 textDocument/didOpen: \27[93munlocked (waiting clangd)\27[0m\27[0m\n"
[ERROR][2023-02-25 16:48:29] .../vim/lsp/rpc.lua:733	"rpc"	"arduino-language-server"	"stderr"	"16:48:29.657309 \27[96mINIT --- : error starting clang: running /usr/bin/arduino-cli --config-file /home/austin/.arduino15/arduino-cli.yaml compile --fqbn esp32:esp32:heltec_wifi_kit_32 --only-compilation-database --source-override /tmp/950932890 --build-path /tmp/arduino-language-server443605573 --format json /home/austin: exit status 1\27[0m\n16:48:29.657338 \27[92m                 textDocument/didOpen: \27[93mlocked (waiting clangd)\27[0m\27[0m\n16:48:29.657344 \27[92m                 textDocument/didOpen: clangd startup failed: quitting Language server\27[0m\n"
`

**Comment by HannHank** [comment]
Okay,
I have the exact same error. And if I try running the arduino-language-server from the comandline, clangd is starting without any problems. So i guess the solution with the least effort would be to downgrade clang, arduino-language-server and the arduino-cli to the version available on your arduino post.  If I find another solution, I'll let you know.

Tank you for confirming the error.

**Comment by HannHank** [comment]
Today I had sometime to look into the issue and discovered that I hat a typo in my board config and then the error changed, complaining about `clangd not found`.  

I have Clangd installed and the path was correct, however the error went away by just removing the explicit path definition `"-clangd", "/usr/bin/clangd"`

Now everything works like a charm. This is my current config with lsp-zero (arduino-cli: 0.31.0, Board: Arduino Uno):
```
lsp.configure('arduino_language_server', {
		on_attach = function(client, bufnr)
		end,
		cmd = { "arduino-language-server",
				"-cli-config", "/home/username/.arduino15/arduino-cli.yaml",
				"-fqbn", "arduino:avr:uno",
				"-cli", "/usr/bin/arduino-cli",
		}
})

```
